### ISSUE TITLE
device_manager_old.py, WifiReceive.py, example.py

### ISSUE THREAD

**Issue by TSomann** [epicframework/EPIC-Core#1]
Do these server any purpose with the updated DeviceManager (formerly BroadcastClient)?

**Comment by bradyjibanez** [comment]
From what I recall, I had my hand in the making of WifiReceive. It is a misnomer from what I didn't understand in the initial making of it, and it was only good to interact with the constantly looping manual Broadcast client that existed a long time ago. So, I'm pretty confident in saying that one has no place with the updated version, nor should it, though the concept it holds of devices acting as individual servers interacted with by the one governing client (signal receiver) is there.
